Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CalendarEvents.Models.VMs;
using CalendarEvents.Data;
using CalendarEvents.Models.Objs;

namespace CalendarEvents.Controllers
{
    public class EventsController : Controller
    {
        private readonly IDAL _dal;

        public EventsController(IDAL dal)
        {
            _dal = dal;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var vms = _dal.GetAllEvents().ToArray()
                               .Select(c => new EventVM(c))
                               .ToList();
            return View(vms);

        }

        //GET: Events
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var vm = new EventVM();
            vm.StartTime = DateTime.Now;
            vm.EndTime = DateTime.Now + TimeSpan.FromDays(1);
            vm.Locations = new SelectList(_dal.GetAllLocations().ToList(), "Id", "Name");

            return View(vm);
        }


        // POST: Events
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventVM vm)
        {
            // vm.LocationName = await _context.Locations.FindAsync(vm.LocationId).Name;

            /* 
             if (!ModelState.IsValid)
             {
                 vm.Locations = new SelectList(_context.Locations.ToList(), "id", "Name");
                 ModelState.AddModelError("Error!", "Some values are missing!");
                 return View(vm);
             }
           */
            var obj = new Event
            {
                Name = vm.Name,
                Description = vm.Description,
                LocationId = vm.LocationId,
                StartTime = vm.StartTime,
                EndTime = vm.EndTime,
                LocationName = _dal.GetLocation(vm.LocationId).Name
            };

            _dal.AddEvent(obj);

            return RedirectToAction(nameof(Index));
        }
            /*
                    // GET: Events/Details/5
                    public async Task<IActionResult> Details(int? id)
                    {
                        if (id == null || _context.Events == null)
                        {
                            return NotFound();
                        }

                        var @event = await _context.Events
                            .Include(@ => @.Location)
                            .FirstOrDefaultAsync(m => m.id == id);
                        if (@event == null)
                        {
                            return NotFound();
                        }

                        return View(@event);
                    }

                    // GET: Events/Create
                    public IActionResult Create()
                    {
                        ViewData["LocationId"] = new SelectList(_context.Locations, "id", "id");
                        return View();
                    }

                    // POST: Events/Create
                    // To protect from overposting attacks, enable the specific properties you want to bind to.
                    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
                    [HttpPost]
                    [ValidateAntiForgeryToken]
                    public async Task<IActionResult> Create([Bind("id,Name,description,StartTime,EndTime,LocationId,LocationName")] Event @event)
                    {
                        if (ModelState.IsValid)
                        {
                            _context.Add(@event);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));
                        }
                        ViewData["LocationId"] = new SelectList(_context.Locations, "id", "id", @event.LocationId);
                        return View(@event);
                    }

                    // GET: Events/Edit/5
                    public async Task<IActionResult> Edit(int? id)
                    {
                        if (id == null || _context.Events == null)
                        {
                            return NotFound();
                        }

                        var @event = await _context.Events.FindAsync(id);
                        if (@event == null)
                        {
                            return NotFound();
                        }
                        ViewData["LocationId"] = new SelectList(_context.Locations, "id", "id", @event.LocationId);
                        return View(@event);
                    }

                    // POST: Events/Edit/5
                    // To protect from overposting attacks, enable the specific properties you want to bind to.
                    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
                    [HttpPost]
                    [ValidateAntiForgeryToken]
                    public async Task<IActionResult> Edit(int id, [Bind("id,Name,description,StartTime,EndTime,LocationId,LocationName")] Event @event)
                    {
                        if (id != @event.id)
                        {
                            return NotFound();
                        }

                        if (ModelState.IsValid)
                        {
                            try
                            {
                                _context.Update(@event);
                                await _context.SaveChangesAsync();
                            }
                            catch (DbUpdateConcurrencyException)
                            {
                                if (!EventExists(@event.id))
                                {
                                    return NotFound();
                                }
                                else
                                {
                                    throw;
                                }
                            }
                            return RedirectToAction(nameof(Index));
                        }
                        ViewData["LocationId"] = new SelectList(_context.Locations, "id", "id", @event.LocationId);
                        return View(@event);
                    }

            

        }
        */
            // GET: Events/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null || _dal.GetEvent(id) == null)
            {
                return NotFound();
            }

            _dal.DeleteEvent(id);

            return RedirectToAction("Index");
        }

            
    }
}

Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CalendarEvents.Data;
using CalendarEvents.Models.Objs;

namespace CalendarEvents.Controllers
{
    public class LocationsController : Controller
    {
        private readonly CalendarEventsContext _context;

        public LocationsController(CalendarEventsContext context)
        {
            _context = context;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
              return _context.Locations != null ? 
                          View(await _context.Locations.ToListAsync()) :
                          Problem("Entity set 'CalendarEventsContext.Locations'  is null.");
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Locations == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/EditLocation/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Locations == null)
            {
                return NotFound();
            }

            var location = await _context.Locations.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // POST: Locations/EditLocation/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Locations == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Locations == null)
            {
                return Problem("Entity set 'CalendarEventsContext.Locations'  is null.");
            }
            var location = await _context.Locations.FindAsync(id);
            if (location != null)
            {
                _context.Locations.Remove(location);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
          return (_context.Locations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calendar Events</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/js/fullcalendar/calendar.js"></script>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalendarEvents</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalendarEvents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/fullcalendar/prism.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>